function ops = set_options(varargin)
% Known parameters from Meng, Kramer, et al., 2014 Equation (3)

ops = struct(...
	'noiseStd',	'[1 0 0 0]', ... % Integration options
	'delta',	'0.01', ...
	'W',		'5', ...	% Conditional intensity options
	'Vth',		'30', ...
	'hh',		'1/5', ...
	'b',		'h/10' ...
);

for i = 1:2:nargin
	ops.(varargin{i}) = varargin{i + 1};
	if ~ischar(varargin{i}) || ~ischar(varargin{i + 1})
		error('All arguments should be given as strings.')
	end
end
end

% 	'mInf',		'1./(1 + exp((-V-34.5)/10))', ...	% HH options
% 	'nInf',		'1./(1 + exp((-V-29.5)/10))', ...
% 	'hInf',		'1./(1 + exp((V+59.4)/10.7))', ...
% 	'tauN',		'0.25 + 4.35*exp(-abs(V+10)/10)', ...
% 	'tauH',		'0.15 + 1.15./(1 + exp((V+33.5)/15))', ...
% 	'BInf',		'1./(1 + exp(-(V-VBth)./SB))', ...
% 	'tauB',		'tauB', ...
% 	'C',		'0.9', ...
% 	'EK',		'-95', ...
% 	'ENa',		'50', ...
% 	'EL',		'-70', ...
% 	'gNa',		'100', ...
% 	'gK',		'7', ...
% 	'gL',		'0.25', ...